_teknoo_paas_admin_job_list:
    path: '/jobs'
    methods: ['GET']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        loader: '@Teknoo\East\Paas\Loader\JobLoader'
        defaultOrderDirection: 'ASC'
        itemsPerPage: 20
        template: '@@TeknooEastWebsite/AdminJob/list.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/404.html.twig'

_teknoo_paas_admin_job_delete:
    path: '/job/delete/{id}'
    methods:  ['GET']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        nextRoute: 'admin_job_list'
        loader: '@Teknoo\East\Paas\Loader\JobLoader'
        deleter: '@teknoo.east.paas.deleting.job'
        route: '_teknoo_paas_admin_job_list'
        errorTemplate: '@@TeknooEastWebsite/Error/404.html.twig'
