##Account
_teknoo_paas_admin_account_list:
    path: '/accounts'
    methods:  ['GET']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/404.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\East\Paas\Loader\AccountLoader'
        template: '@@TeknooEastPaas/AdminAccount/list.html.twig'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"

_teknoo_paas_admin_account_edit:
    path: '/account/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.paas.endpoint.admin.edit.account'
        errorTemplate: '@@TeknooEastCommon/Error/404.html.twig'
        formClass: 'Teknoo\East\Paas\Infrastructures\Doctrine\Form\Type\AccountType'
        formOptions:
            "doctrine_type": "%teknoo.east.common.form_type.doctrine.class%"
            namespace_in_readonly: true
        loader: '@Teknoo\East\Paas\Loader\AccountLoader'
        template: '@@TeknooEastPaas/AdminAccount/edit.html.twig'
        writer: '@Teknoo\East\Paas\Writer\AccountWriter'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"

_teknoo_paas_admin_account_new:
    path: '/account/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.paas.endpoint.admin.new.account'
        errorTemplate: '@@TeknooEastCommon/Error/404.html.twig'
        formClass: 'Teknoo\East\Paas\Infrastructures\Doctrine\Form\Type\AccountType'
        formOptions:
            "doctrine_type": "%teknoo.east.common.form_type.doctrine.class%"
        loader: '@Teknoo\East\Paas\Loader\AccountLoader'
        objectClass: 'Teknoo\East\Paas\Object\Account'
        route: '_teknoo_paas_admin_account_edit'
        template: '@@TeknooEastPaas/AdminAccount/new.html.twig'
        writer: '@Teknoo\East\Paas\Writer\AccountWriter'
        cleanHtml: "%teknoo.east.paas.admin.rendering.clean_html%"

_teknoo_paas_admin_account_delete:
    path: '/account/delete/{id}'
    methods:  ['GET']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.east.paas.deleting.account'
        errorTemplate: '@@TeknooEastCommon/Error/404.html.twig'
        loader: '@Teknoo\East\Paas\Loader\AccountLoader'
        route: '_teknoo_paas_admin_account_list'
