parameters:
    teknoo.east.paas.symfony.form_type.cluster.class: 'Teknoo\East\Paas\Infrastructures\Symfony\Form\Type\ClusterType'

    teknoo.east.paas.symfony.form_type.cluster.types: { 'Kubernetes': 'kubernetes' }

services:
    teknoo.east.paas.symfony.form_type.cluster:
        class: '%teknoo.east.paas.symfony.form_type.cluster.class%'
        arguments:
            - '%teknoo.east.paas.symfony.form_type.cluster.types%'
        tags: ['form.type']

    teknoo.east.paas.endpoint.admin.new.account:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Paas\Contracts\Recipe\Plan\NewAccountEndPointInterface'
            - '@service_container'

    teknoo.east.paas.endpoint.admin.new.project:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Paas\Contracts\Recipe\Plan\NewProjectEndPointInterface'
            - '@service_container'


    teknoo.east.paas.endpoint.admin.edit.account:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Paas\Contracts\Recipe\Plan\EditAccountEndPointInterface'
            - '@service_container'

    teknoo.east.paas.endpoint.admin.edit.project:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Paas\Contracts\Recipe\Plan\EditProjectEndPointInterface'
            - '@service_container'
