parameters:
    teknoo.east.symfony.normalizer.east_normalizer.class: 'Teknoo\East\Paas\Infrastructures\Symfony\Normalizer\EastNormalizer'
    teknoo.east.paas.symfony.form_type.cluster.types: { 'Kubernetes': 'kubernetes', 'Docker Swarm': 'swarm' }
    teknoo.east.paas.symfony.history.prefer-real-date: true

services:
    teknoo.east.paas.symfony.property_accessor:
        class: 'Symfony\Component\PropertyAccess\PropertyAccessor'
        public: true
        arguments:
            - false
            - false
            - '@?cache.property_access'

    Teknoo\East\Paas\Infrastructures\Symfony\Normalizer\ExceptionNormalizer:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Normalizer\ExceptionNormalizer'
        tags:
            - {name: 'serializer.normalizer', priority: 100}

    Teknoo\East\Paas\Infrastructures\Symfony\Normalizer\ClassFinderDenormalizer:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Normalizer\ClassFinderDenormalizer'
        calls:
            - ['setDenormalizer', ['@serializer']]
        tags:
            - {name: 'serializer.normalizer', priority: 10}

    Teknoo\East\Paas\Infrastructures\Symfony\Normalizer\HistoryDenormalizer:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Normalizer\HistoryDenormalizer'
        tags:
            - {name: 'serializer.normalizer', priority: 100}

    Teknoo\East\Paas\Infrastructures\Symfony\Normalizer\JobUnitDenormalizer:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Normalizer\JobUnitDenormalizer'
        calls:
            - ['setDenormalizer', ['@serializer']]
        tags:
            - {name: 'serializer.normalizer', priority: 100}

    Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Forward\HistorySentHandler:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Forward\HistorySentHandler'
        tags:
            - 'messenger.message_handler'

    Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Forward\JobDoneHandler:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Forward\JobDoneHandler'
        tags:
            - 'messenger.message_handler'

    Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Command\DisplayHistoryHandler:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Command\DisplayHistoryHandler'

    Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Command\DisplayResultHandler:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Command\DisplayResultHandler'

    Teknoo\East\Paas\Infrastructures\EastPaasBundle\Subscriber\CommandSubscriber:
        class: 'Teknoo\East\Paas\Infrastructures\EastPaasBundle\Subscriber\CommandSubscriber'
        arguments:
            - '@Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Command\DisplayHistoryHandler'
            - '@Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Command\DisplayResultHandler'
            - '@Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Forward\HistorySentHandler'
            - '@Teknoo\East\Paas\Infrastructures\Symfony\Messenger\Handler\Forward\JobDoneHandler'
        tags:
            - { name: 'kernel.event_subscriber' }

    teknoo.east.paas.symfony.command.run_job:
        parent: 'Teknoo\East\Paas\Infrastructures\Symfony\Command\RunJobCommand'
        tags:
            - {name: 'console.command' }

    Teknoo\East\Paas\Infrastructures\Symfony\Recipe\Step\Worker\DispatchJob:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Recipe\Step\Worker\DispatchJob'
        public: true
        arguments:
            - '@messenger.default_bus'

    Teknoo\East\Paas\Infrastructures\Symfony\Recipe\Step\History\SendHistory:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Recipe\Step\History\SendHistory'
        public: true
        arguments:
            - '@Teknoo\East\Website\Service\DatesService'
            - '@messenger.default_bus'
            - '%teknoo.east.paas.symfony.history.prefer-real-date%'

    Teknoo\East\Paas\Infrastructures\Symfony\Recipe\Step\Job\PushResult:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Recipe\Step\Job\PushResult'
        public: true
        arguments:
            - '@Teknoo\East\Website\Service\DatesService'
            - '@messenger.default_bus'
            - '@Teknoo\East\Paas\Contracts\Serializing\NormalizerInterface'
            - '@Teknoo\East\Paas\Contracts\Response\ErrorFactoryInterface'
            - '%teknoo.east.paas.symfony.history.prefer-real-date%'

    Teknoo\East\Paas\Infrastructures\Symfony\Serializing\Deserializer:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Serializing\Deserializer'
        public: true
        arguments:
            - '@serializer'

    Teknoo\East\Paas\Infrastructures\Symfony\Serializing\Normalizer:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Serializing\Normalizer'
        public: true
        arguments:
            - '@serializer'

    Teknoo\East\Paas\Infrastructures\Symfony\Serializing\Serializer:
        class: 'Teknoo\East\Paas\Infrastructures\Symfony\Serializing\Serializer'
        public: true
        arguments:
            - '@serializer'

