parameters:
    teknoo.east.paas.symfony.end_point.new_account.class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
    teknoo.east.paas.symfony.end_point.new_job.class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
    teknoo.east.paas.symfony.end_point.job_add_history.class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
    teknoo.east.paas.symfony.end_point.job_run.class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'

    teknoo.east.paas.symfony.end_point.new_job.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.paas.symfony.end_point.job_add_history.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.paas.symfony.end_point.job_run.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'

services:
    ### new_job
    teknoo.east.paas.symfony.end_point.new_job.bowl:
        class: '%teknoo.east.paas.symfony.end_point.new_job.bowl.class%'
        arguments:
            - '@Teknoo\East\Paas\Contracts\Recipe\Cookbook\NewJobInterface'
            - 0

    teknoo.east.paas.symfony.end_point.new_job:
        class: '%teknoo.east.paas.symfony.end_point.new_job.class%'
        public: true
        arguments:
            - '@teknoo.east.paas.symfony.end_point.new_job.bowl'

    ### job_add_history
    teknoo.east.paas.symfony.end_point.job_add_history.bowl:
        class: '%teknoo.east.paas.symfony.end_point.job_add_history.bowl.class%'
        arguments:
            - '@Teknoo\East\Paas\Contracts\Recipe\Cookbook\AddHistoryInterface'
            - 0

    teknoo.east.paas.symfony.end_point.job_add_history:
        class: '%teknoo.east.paas.symfony.end_point.job_add_history.class%'
        public: true
        arguments:
            - '@teknoo.east.paas.symfony.end_point.job_add_history.bowl'

    ### job_run
    teknoo.east.paas.symfony.end_point.job_run.bowl:
        class: '%teknoo.east.paas.symfony.end_point.job_run.bowl.class%'
        arguments:
            - '@Teknoo\East\Paas\Contracts\Recipe\Cookbook\RunJobInterface'
            - 0

    teknoo.east.paas.symfony.end_point.job_run:
        class: '%teknoo.east.paas.symfony.end_point.job_run.class%'
        public: true
        arguments:
            - '@teknoo.east.paas.symfony.end_point.job_run.bowl'
