Teknoo\East\Paas\Object\ClusterCredentials:
    attributes:
        clientCertificate:
            serialized_name: client_certificate
        token:
            serialized_name: token
        username:
            serialized_name: username
        password:
            serialized_name: password