Teknoo\East\Paas\Object\ClusterCredentials:
  attributes:
    serverCertificate:
      serialized_name: server_certificate
    privateKey:
      serialized_name: private_key
    publicKey:
      serialized_name: public_key