Teknoo\East\Paas\Object\ClusterCredentials:
    attributes:
        serverCertificate:
            serialized_name: server_certificate
        token:
            serialized_name: token
        username:
            serialized_name: username
        password:
            serialized_name: password